### ISSUE TITLE
requirements.txt not found

### ISSUE THREAD

**Issue by Mr-Phil1** [aibix0001/aasil#1]
Die in der readme.md erwähnte Datei `requirements.txt` ist zum aktuellem Zeitpunkt ind den Dateien nicht auffindbar.
*Vermutlich ist diese Datei im Bereich `.venv` zu finden, und dieser wird ja durch einen Eintrag in der `.gitignore` Datei ignoriert.*

**Comment by aibix0001** [comment]
Hinzugefügt.
